baseURL = 'https://naviji.github.io/website/'
languageCode = 'en-us'
title = 'Naveen M V'
theme = 'lithium'

[params]
    [params.logo]
        url = "logo.png"
        width = 50
        height = 50
        alt = "Logo"

    [params.icon]
        url = "favicon.ico"

    [params.title]
        name = "Naveen M V"
